# Site settings
title: "Kettlesoft"
email: dkettlestrings@gmail.com
description: "Everything I'm Thinking About"
baseurl: ""
url: "https://dkettlestrings.github.io/"
title_description: "This site is about everything I'm thinking about/doing.  Themes tend to focus on software, but not to the exclusion of my other hobbies: brewing, cooking, tinkering, and complaining."
title_image: "./assets/title_image.JPG"
disqus_account: kettlesoft
github_repository: https://github.com/dkettlestrings/dkettlestrings.github.io
post_limit: 5

# Social usernames/URLs
github_username:  dkettlestrings
linkedin_link: https://linkedin.com/in/david-kettlestrings/

# Footer
footer_left: "<a href=\"https://github.com/jacobtomlinson/carte-noire\">Carte Noir</a> theme by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "Site source on <a href=\"https://github.com/dkettlestrings/dkettlestrings.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
